### ISSUE TITLE
List of the test cases

### ISSUE THREAD

**Issue by benfab** [cloudfoundry/cf-smoke-tests#33]
Hello,

I would be great to have a list of test cases as part of the documentation in order to see at glance what tests are being executed.

Thanks!

**Comment by dsabeti** [comment]
@benfab. It sounds like you're asking for an update to the README that explains each test that gets run. Am I understanding you correctly?

If so, I think we should focus instead on making the tests more readable and discoverable. I hesitate to lean too heavily on documentation because it goes out of date. If we found a way to make the test code easier to understand, do you think that would help you out?

**Comment by benfab** [comment]
@dsabeti I am looking for a simple way to understand quickly what is being executed by the tests.
It doesn't require to be an exhaustive description of the tests, few lines in the README explaining that org, space, user are created and then some testing apps pushed and deleted would be a good start.

**Comment by dsabeti** [comment]
Thanks for the feedback. How do this look now? https://github.com/cloudfoundry/cf-smoke-tests/commit/3dfb50981a50b456dd2c814c913c8ccdaa96ceb4

**Comment by benfab** [comment]
@dsabeti Great, that definitely helps! Thanks!
