### ISSUE TITLE
Versioned Binaries of Smoke Test

### ISSUE THREAD

**Issue by Salamandastron1** [cloudfoundry/cf-smoke-tests#63]
We would love some versioned binaries that can be run idempotently.

This would reduce the toil of our customers needing to configure `go` in environments that don't necessarily call for it.

Also allows the tests to more easily be run at scale or in pipelines.

Ala `ginkgo build -r /test/directory/`

**Comment by ericpromislow** [comment]
Hi @Salamandastron1 

We've discussed this a fair bit.

On one hand, since `cf-smoke-tests` aren't a standalone product, a binary release would have to be part of another release, most likely a bosh release, and on a cadence that might not make sense.

On the other hand, `cf-smoke-tests` is an open-source project (Apache), and you're welcome to take that source, and build and distribute any products from it within the terms of the license. Which while IANAL, I don't see a problem. Clause 4.a requires you make the license available to any people who would get this executable; wrapping the executable and a copy of the license in a zip file should be good enough.

We've got a lot on our plate right now, so we're going to go with option 2 for now. Please feel free to reopen this issue if you have other concerns.

Thanks for bringing this up (and for letting me learn about `ginkgo build` -- I had no idea),
Eric Promislow, Release Integration Community Team
